require("aerial").setup {
  backends = { "treesitter", "lsp", "markdown", "man" },
  layout = {
    max_width = { 40, 0.2 },
    width = nil,
    min_width = 25,
    default_direction = "prefer_right",
    placement = "window",
  },
  -- Attach to all windows — needed for distributed systems / large file nav
  attach_mode = "global",
  -- Show all symbol kinds
  filter_kind = false,
  icons = {
    -- Codicons range (U+EA60-U+EBEB) — Nerd Fonts v2/v3 compatible
    -- file = " ",
    -- module = " ",
    -- namespace = " ",
    -- package = " ",
    -- class = " ",
    -- method = " ",
    -- property = " ",
    -- field = " ",
    -- constructor = " ",
    -- enum = " ",
    -- interface = " ",
    -- function = " ",
    -- variable = " ",
    -- constant = " ",
    -- string = " ",
    -- number = " ",
    -- boolean = " ",
    -- array = " ",
    -- object = " ",
    -- key = " ",
    -- null = " ",
    -- enummember = " ",
    -- struct = " ",
    -- event = " ",
    -- operator = " ",
    -- typeparameter = " ",
  },
  show_guides = true,
  guides = {
    mid_item = "├─ ",
    last_item = "└─ ",
    nested_top = "│  ",
    whitespace = "   ",
  },
  keymaps = {
    ["?"] = "actions.show_help",
    ["<cr>"] = "actions.jump",
    ["<2-leftmouse>"] = "actions.jump",
    ["<c-v>"] = "actions.jump_vsplit",
    ["<c-s>"] = "actions.jump_split",
    ["p"] = "actions.scroll",
    ["<c-j>"] = "actions.down_and_scroll",
    ["<c-k>"] = "actions.up_and_scroll",
    ["{"] = "actions.prev",
    ["}"] = "actions.next",
    ["[["] = "actions.prev_up",
    ["]]"] = "actions.next_up",
    ["q"] = "actions.close",
  },
  on_attach = function(bufnr)
    -- telescope integration loaded after setup
    pcall(require("telescope").load_extension, "aerial")
  end,
}
