# Window navigation
bind ^H previous-window
bind ^L next-window
bind w list-windows
bind '"' choose-window
bind r command-prompt "rename-window %%"
bind ^A last-window

# Session / client
bind ^D detach
# bind ^L refresh-client
bind -n C-l refresh-client
bind S choose-session

# Panes
bind z resize-pane -Z
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Window management
bind c new-window -c "#pane_current_path"

# Panes management
bind x kill-pane
bind X kill-pane

# Pane navigation (keep clean hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane-pane -R

# Resize (prefix + , . - =)
bind -r , resize-pane -L 20
bind -r . resize-pane -R 20
bind -r - resize-pane -D 7
bind -r = resize-pane -U 7

# Misc
bind : command-prompt
bind K send-keys "clear" \; send-keys Enter
bind a swap-pane -D
bind * setw synchronize-panes
bind P set pane-border-status

# Reload
bind R source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# Copy-mode selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
